### ISSUE TITLE
Is it possible to do away with method_missing/instance_eval?

### ISSUE THREAD

**Issue by hoelzro** [gavinlaking/vedeu#110]
While playing with vedeu, I've found that the usage of `instance_eval` often surprises me.  Sometimes a block supplied to a vedeu method preserves the original self; other times, I need to squirrel away a reference to the current self in another variable so that I may refer to it in the block.  As far as I can tell, there are two ways to get around needing `instance_eval`:

  - Supply the current object you're working on to the block (similar to `Gem::Specification.new`)
  - Build up context in the methods, and have the vedeu API methods recognize which context they're being called in.

The former is probably cleaner but would break backwards compability, and the latter seems to have the opposite advantages/disadvantages.  I understand this would be a great undertaking, but I wanted to point this out and hopefully promote some discussion on the matter; perhaps we can find a better way than the examples I offered above!

**Comment by tristil** [comment]
I'm running into the same issue of not being able to refer to methods on the instance inside of a render block. The syntax that @hoelzro suggests has the advantage that it will be more familiar to Rails developers.

**Comment by gavinlaking** [comment]
Hi,

As far as I know, the block is optional in the sense that if you provide it, you're helping Ruby and not providing it means you're at the mercy of local and binding scopes (depending on whether you are inside or out). Vedeu will execute code fro the class in the block's scope. An example of this can be found in Playa. (https://github.com/gavinlaking/playa/blob/master/lib/playa/views/playlist_view.rb)

This code relies on an old version of Vedeu (yes, I must update it!) but I spent around 6 weeks during December and January refactoring and improving the DSL based on @hoelzro's feedback. I've not closed this issue because I didn't remove instance_eval in the end.

I agree more work is needed in this area, but I'm scraping a barrel on what to do barring update the documentation to reflect the 'Rails'/'usual Ruby block' way of doing things is also supported.

Any ideas on how we can move this forward?

Gav

**Comment by tristil** [comment]
I think there's something I'm not following. I might not be using the DSL correctly. To be clear this gist describes the problem I'm running into:

https://gist.github.com/tristil/77c6d196514d6de6504e

**Comment by gavinlaking** [comment]
What happens if you use `Vedeu.renders`? Also, do you get any mileage from being really verbose about the block; i.e.

```ruby
def show
    Vedeu.renders do |views|
      views.view 'myinterface' do |content|
        content.lines do |body|
          body.line something
        end
      end
    end
  end
```

I can't check at the moment, but will do shortly, sorry!

Gav

**Comment by gavinlaking** [comment]
I've just been thinking about this a little more (but still can't check for myself). Does the addition of parenthesis help at all?

```ruby
def show
  Vedeu.renders do |views|
    views.view 'myinterface' do |content|
      content.lines do |body|
        body.line(something) # parenthesis added to help Ruby
      end
    end
  end
end
```

**Comment by tristil** [comment]
No, those don't change the result. The problem to be clear is that it's evaluating things in the class context, not the instance context...

So it looks like the key was that I was creating the interfaces in the body of the class. If I instead create the interfaces inside a `#setup` method then I can use an instance method inside the block, because the context is now the instance.

I think what was confusing here is that to my mind it makes sense to create views from within instance methods (but maybe this is a misunderstanding of how views should be setup?), but the examples of defining interfaces are usually inside class bodies.

**Comment by gavinlaking** [comment]
Damn! :-1:

I think views should be created inside instance methods of a class despite Vedeu not appearing to work in that way without messing around, which is a shame. I will have a look at this code with fresher eyes (it was around 6 months ago I last did work in this area) and see if I can create a solution for this. If you stumble upon a solution before I do, please submit a pull-request!

Thanks again,

Gav
