### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by gavinlaking** [gavinlaking/vedeu#157]
The RubyDoc is starting to take shape, but this offers no clues to developers who want to use Vedeu in their own projects. Where do you start?! More work is needed in this area to really let Vedeu shine.

**Comment by tristil** [comment]
I was about to open a new ticket where I was going to list out questions that are slowing me down in using Vedeu, but maybe I can just put them here. Let me know if you want me to put them somewhere else.

1. What is an idiomatic way to position the cursor? Specifically I want the cursor to alway be on the 4th X position when my middle pane is focused. What I'm working with now is binding the `_focus_next_` event and then I guess manually moving the cursor over by triggering `_cursor_right_` but that doesn't sound right.
2. The way events are used in Vedeu is interesting but somewhat unusual for GUI programming IMO in the extent to which you use events to query for information in addition to listening to events. It would be good to talk about the philosophy and approach around events used here. It would also be good to talk about considerations with events: do they propagate to containing objects, can you stop the chain, etc.?
3. Similarly it might be good to talk about good design practice wrt structuring MVC. This project reminds me of Backbone where it seems like the view block should be organized in a way to facilitate a kind of data binding, but this is handled in a purely conventional fashion. That is, the best practice is to change state in your models and then trigger a refresh to update the view, which does the right thing, rather than trying to manually update parts of the page. Anyway it might be good to talk about "best practices for building a Vedeu application".

That's all I have at the moment but I will probably encounter other things.

**Comment by gavinlaking** [comment]
Hi @tristil,

Thanks for the questions :-) I'll try and tackle them here, but I'll also break them out into separate issues so that we can discuss them individually and reach some resolution with them. (Resolution is probably writing some code!)

1) At the moment, there isn't an idiomatic way to position the cursor when a view is focussed, and I think there should be, so I'll jump on that because I think I have an idea how to do it.

2) I have organically mixed querying events with command events as perceived need has arose. It would be nice to have a clear boundary, but I think that sometimes you need some information via a query that needs to occur "out-of-band". I'm not sure if this is bad design, or just a weird way to go about it. Vedeu is nothing short of evolution codified. At the moment, they kind of work separately to the containing object, but this is/was to allow more flexibility. Also, at the moment there is no way to stop the chain. Once you fire an event, then whatever that event defines will be triggered also, this makes for an interesting call stack if you create unintentional loops (I hope nobody does that, it would be a nightmare to debug.) It would be nice to stop the chain, and I think I'd really like the events to fire on separate threads but I'm not sure on how to achieve that yet. 

3) The MVC pattern which I'm trying to build via the 'generator' stuff is the direction I would like to take Vedeu, so that one could build a sane application. Vedeu has its many feet in many different camps though (standalone script, one-off utility, client application). I don't want to remove any existing functionality, but I do believe it could be structured better, and I think that documentation will really help here. I have a lot of how Vedeu works encoded in my head and that's not really the best place for it.

Please keep firing the questions at me, and I'll try to work through them and give answers in written or code form and via this approach, I think we'll make Vedeu a lot better, and much easier to use.

Gav

**Comment by tristil** [comment]
New question: In my Curses-based code I had a utility function that I used to kill Curses and open up a debugger: https://github.com/tristil/minder/blob/master/lib/minder.rb#L36 . This is what I tried as the equivalent code with the Vedeu code: https://github.com/tristil/minder/blob/migrate_to_vedeu/lib/minder.rb#L37 This doesn't seem to work for me. Do you have something similar or is this what the drb server is for or what?
