### ISSUE TITLE
Events: Queries & Commands

### ISSUE THREAD

**Issue by gavinlaking** [gavinlaking/vedeu#164]
Courtesy of @tristil:

The way events are used in Vedeu is interesting but somewhat unusual for GUI programming IMO in the extent to which you use events to query for information in addition to listening to events. It would be good to talk about the philosophy and approach around events used here. It would also be good to talk about considerations with events: do they propagate to containing objects, can you stop the chain, etc.?

**Comment by gavinlaking** [comment]
The `bindings.rb` file current contains all of the events which Vedeu defines. There is a mix of 'query' events (they fetch information for you to use) and 'command' events (they instruct Vedeu to do something for you).

I think this file should be broken down into two files; a `query_bindings.rb` and `command_bindings.rb`.

From #157:

I have organically mixed querying events with command events as perceived need has arose. It would be nice to have a clear boundary, but I think that sometimes you need some information via a query that needs to occur "out-of-band". I'm not sure if this is bad design, or just a weird way to go about it. Vedeu is nothing short of evolution codified. At the moment, they kind of work separately to the containing object, but this is/was to allow more flexibility. Also, at the moment there is no way to stop the chain. Once you fire an event, then whatever that event defines will be triggered also, this makes for an interesting call stack if you create unintentional loops (I hope nobody does that, it would be a nightmare to debug.) It would be nice to stop the chain, and I think I'd really like the events to fire on separate threads but I'm not sure on how to achieve that yet.

**Comment by gavinlaking** [comment]
Of the events currently defined, only 6 are query events, the rest are command events.

**Comment by tristil** [comment]
To be clear, I'm not opposed to using query events or even certain that it's that unusual. I've just never seen it before. To do a pro/con: 

Pro: 

- using events for queries and commands gives you a more consistent interface
- query events can lead to a more decoupled style if they help hide implementation details of where exactly an element is in the object graph, sort of like using jQuery to query the dom relative to an element.
- You don't have as much need to climb out of your context to get state (I mean code like `parent.parent.window`).

Con:

- Queries on state just aren't events, and this will be confusing for people who have done event-driven programming before.
- What is it about the design that prevents you from looking up state on the object graph directly within command event callbacks? That is, why can't you just say `cursor.position` within a `_focused_` or `_refresh_` callback?

**Comment by gavinlaking** [comment]
Just looking at the Cons. I think for the few query events which are defined, I was looking to provide a convenient way to determine certain information about the client application and/or Vedeu. I think that reaching into the internals of Vedeu might not be the right way to go as it might mean that if classes and structure changes, it will affect client applications. By providing the events, I can reduce the public interface of Vedeu and means I'm more free to change how and where things are (which is probably important since I do change them quite often as I'm tidying up and "trying to make it better".).

A way to tackle this, would be to move these events to API methods (of the form `Vedeu.some_method`). This way I won't confuse people who have done event-driven programming. (I have to admit here, that I haven't done it before which is probably why my take on it is a little twisted!).

I'm really open to suggestions (and obviously pull-requests), so if you think something could/should change, please guide me.

Gav

**Comment by tristil** [comment]
Been messing around on my Vedeu migration branch and have some more thoughts about events. 

FWIW, here is what I am used to with event systems:

1. GUI element **A** receives a low-level event (say a keypress)
2. **A** has a listener bound to this event.
3. **A** handles this event locally with no need for further action OR:
4. **A** reaches out to its object graph (parent GUI elements, etc.) and invokes an action OR:
5. **A** puts a new higher-level message onto a message bus/some global listener that other events can respond to. (the lack of a bus is why my program has this monster case statement: https://github.com/tristil/minder/blob/master/lib/minder/application.rb#L105)

Basically the goal is to reduce coupling by making the sender of the event ignorant of what the consumers of the event will do with it, and by letting actions get resolved at the right level of locality. 

So here is how I'm trying to implement this kind of eventing in my code:

```ruby
# views/keymaps/tasks.rb

Vedeu.keymap('tasks') do
  key('?') { Vedeu.trigger(:show_help) }
end

# views/keymaps/help.rb
module Cli2
  class HelpView < Vedeu::ApplicationView
    def initialize(*)
      super
      Vedeu.bind(:show_help) do
        Vedeu.trigger(:_show_interface_, 'help')
      end
    end
  end
end
```

I think what's unusual for me is that even though I'm receiving the event in a View I then have to send off again to have some other service (that I'm ignorant of, a good thing in itself) actually show the help interface. I'm confused about why I can't just say okay, show the view that just received this message. Well, I mean, I know why; it's because the binding here doesn't really belong to the view, but I think maybe that is a drawback.

Really, these are my questions/confusions atm:

1. Conceptually, what is the difference between a View, an Interface, and a Buffer? It doesn't seem like an Interface can be associated with multiple views, so are Views and Interfaces always 1:1? It seems like a Buffer is an internal implementation detail of a View but it's the thing that actually gets `#show`, etc. called on it. 
2. In my event callback is there a way for me to get to the associated buffer for the current view I'm in to call `show` on it? Is that even a thing? Is direct access to a buffer the kind of thing that you're trying to hide from the public interface? Could you finesse this by delegating all the buffer access through the View instance? Why can't I call `show` on the View instance?

Hope this is useful.

**Comment by gavinlaking** [comment]
Aha! You've landed in a little trap I set for myself and have been trying mentally to remove for a while. Views, Interfaces and Buffers are the same thing. They are different perspectives of the same thing. A View represents something you would like to send to a Buffer. The Interface defines the parameters and constraints of the view. The Buffer is the actual 'ready to render next' version of the view.

`Interface -> View -> Buffer`

I'd love to rename these all to view and simplify this part, but the task is tricky, not least of which because of naming.

In point 1, you are absolutely right. It is a means to have a 'next up', a 'currently being displayed' and 'what was displayed last'. This concept is needed (at least in my mind because you don't want the view to change immediately and a sort of 'double buffering' would be helpful for refreshes which didn't affect a particular view itself but instead those around it. The trick is trying not to have to redraw the whole screen again when only one part of it changed.

I'd prefer to hide the access of a particular buffer since then the client application (and poor developer) is left managing all this state themselves. I thought it better for them to just call 'refresh' for a named view and let Vedeu handle what was next, what should be shown etc.

I think the way I tend to view the client application is that it sets up the initial states of the system via the Interface and related DSLs. The Controller and View parts creating a specific buffer to be displayed at a point in time, and then the event system orchestrating the transitions between these states.

**Comment by gavinlaking** [comment]
From your example above; by setting `controller_name` in your controller (see https://github.com/gavinlaking/vedeu/blob/master/lib/vedeu/application/controller.rb#L13) this event is created for you so all you need to do is trigger it and whatever is in the `#initialize` method of that controller will be run. This is handy because a controller may render many views at once with different model data.

Hope this helps?!
