### ISSUE TITLE
DSL should (optionally, but preferably) accept Symbols instead of Strings

### ISSUE THREAD

**Issue by fwolfst** [gavinlaking/vedeu#239]
To illustrate:

    Vedeu.interface 'main' do                                           
      border 'main' do                                                  
        #...            
      end                                                               
      geometry 'main' do
        #....
      end
    end
    Vedeu.renders do
      view 'main' do
      end
    end

I would prefer to define it as

    Vedeu.interface :main do
    # etc...

I did not investigate why this does not work.

**Comment by fwolfst** [comment]
Weird. It does work now, probably a mistake on my side. Anyway, probably the examples should use the 'symbol' syntax.

**Comment by gavinlaking** [comment]
I think in nearly all cases, you can use a symbol instead of a string for name; however, no coercion is performed by Vedeu meaning that if you store a model by a symbol name, then you must retrieve it by the same symbol name. Likewise for strings.

Perhaps Vedeu could coerce all strings and symbols into just symbols for storage.

**Comment by gavinlaking** [comment]
Thanks for the enhancement idea. The documentation has now largely been updated to reflect symbol names instead of strings.
