### ISSUE TITLE
Editor-example fails if ./tmp directory does not exist

### ISSUE THREAD

**Issue by fwolfst** [gavinlaking/vedeu#283]
If I execute `example/dsl_editor.rb` without the `tmp` folder existing, I get following error.

I think the `log <filename>` directive should try to create the folder and file (and raise if it couldnt).

```
/home/econya/code/contrib/vedeu/lib/vedeu/logging/lockless_log_device.rb:54:in `initialize': No such file or directory @ rb_sysopen - ./tmp/editor.log (Errno::ENOENT)
	from /home/econya/code/contrib/vedeu/lib/vedeu/logging/lockless_log_device.rb:54:in `open'
	from /home/econya/code/contrib/vedeu/lib/vedeu/logging/lockless_log_device.rb:54:in `open_logfile'
	from /home/econya/code/contrib/vedeu/lib/vedeu/logging/lockless_log_device.rb:22:in `initialize'
```

**Comment by gavinlaking** [comment]
Thanks for the heads up on this. I think a better solution, might be to specify the (system) `/tmp` directory instead since both target platforms (Linux/OSX) will have this directory. I think it is safe to assume that if the user is executing the examples, then they have the ability to change the path provided to `log`, if `/tmp` is unsuitable.

I had originally changed this to `./tmp` in the project as it was locally convenient, whilst forgetting that the `.gitignore` file omits this and so therefore the directory will not be part of the repository when cloned. Oops!
