### ISSUE TITLE
Drawing doesn't go to bottom of screen?

### ISSUE THREAD

**Issue by NullVoxPopuli** [gavinlaking/vedeu#338]
Terminal:

![image](https://cloud.githubusercontent.com/assets/199018/11672931/b113b3b6-9de2-11e5-941a-940b4a7a0a8f.png)

App:

![image](https://cloud.githubusercontent.com/assets/199018/11672935/c3a06cc2-9de2-11e5-9a57-d90656b3990e.png)

The bottom row of characters doesn't contain any borders or anything.

**Comment by NullVoxPopuli** [comment]
this occurs on the examples as well.

**Comment by gavinlaking** [comment]
Terminal geometry is the bane of my Vedeu life. Unfortunately, it is the strange mix of arrays starting from 0, and terminals starting at column 1, mixed with a side portion of not knowing whether to add or subtract 1 to determine the actual size expected by the user. :smile:

Please school me here- I am likely wrong!

```
d = 3
dn = 13
```

Here we specify some coordinates (either `x` or `y`, denoted as `d` to mean 'starting dimension' (`dn` to mean 'ending dimension`). This reads as starting at, and including character column/row 3, to ending at, and including character column/row 13. On this premise, these coordinates mean width or height of 10. We reach this via `dn - d`.

```
x = 6
width = 10
```

Here, our `d` is 6, and our `dn` should be `(x + width)`, equalling 16. Again, this gives us 10 character columns. However, there are 11 digits when we count, starting with 1 at 6, to 16. So let's minus 1 to get back to 10. However, `dn` is now `(x + width) - 1)` which is 9. (But with 10 digits).

If I code in this example to minus 1 from the width no matter what, then later ask for the width, I get back 9 (but 10 was specified!). If I don't do that, the number of cells is actually 11- but 10 was specified! (I can't win?!).

I have to hold my hands up here and admit that I get really confused, particularly because I'm trying to align maths with what I think users expect. In the first example, we specified the coordinates and so we know that we should see something 10 characters wide/tall. In the second example, we specified how wide something should be.

Something tells me I'm missing something fundamental here, and I'm reaching out for some gentle assistance on basic mathematics. Luckily a lot of these calculations are around geometry and borders, so should be very easy to clean up, but I want to clean up in the right way.

Please don't think I'm stupid- I don't mind being red-faced for a little while though.

**Comment by gavinlaking** [comment]
For this particular issue it might also be worth me mentioning: http://www.rubydoc.info/gems/vedeu/Vedeu/Terminal#size-class_method

**Comment by NullVoxPopuli** [comment]
ah ok, that makes sense. I remember one of my friends finding a similar issue / weirdness with curses for his terminal app.

**Comment by gavinlaking** [comment]
I'd love to iron this out completely though, so you can expect a few commits which tackle it in various ways. Thank you for your continued patience. :smile:

**Comment by NullVoxPopuli** [comment]
woo! thank you for taking a look at this!
